
package com.froad.client.merchantTraffic;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-04-15T16:38:09.792+08:00
 * Generated source version: 2.3.3
 * 
 */
public final class MerchantTrafficService_MerchantTrafficServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.CB.froad.com/", "MerchantTrafficServiceImplService");

    private MerchantTrafficService_MerchantTrafficServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MerchantTrafficServiceImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MerchantTrafficServiceImplService ss = new MerchantTrafficServiceImplService(wsdlURL, SERVICE_NAME);
        MerchantTrafficService port = ss.getMerchantTrafficServiceImplPort();  
        
        {
        System.out.println("Invoking getMerchantTrafficInfoByUserId...");
        java.lang.String _getMerchantTrafficInfoByUserId_arg0 = "";
        java.util.List<com.froad.client.merchantTraffic.MerchantTraffic> _getMerchantTrafficInfoByUserId__return = port.getMerchantTrafficInfoByUserId(_getMerchantTrafficInfoByUserId_arg0);
        System.out.println("getMerchantTrafficInfoByUserId.result=" + _getMerchantTrafficInfoByUserId__return);


        }
        {
        System.out.println("Invoking addMerchantTraffic...");
        com.froad.client.merchantTraffic.MerchantTraffic _addMerchantTraffic_arg0 = null;
        java.lang.Integer _addMerchantTraffic__return = port.addMerchantTraffic(_addMerchantTraffic_arg0);
        System.out.println("addMerchantTraffic.result=" + _addMerchantTraffic__return);


        }
        {
        System.out.println("Invoking getMerchantTrafficInfoByMerchantId...");
        java.lang.String _getMerchantTrafficInfoByMerchantId_arg0 = "";
        java.util.List<com.froad.client.merchantTraffic.MerchantTraffic> _getMerchantTrafficInfoByMerchantId__return = port.getMerchantTrafficInfoByMerchantId(_getMerchantTrafficInfoByMerchantId_arg0);
        System.out.println("getMerchantTrafficInfoByMerchantId.result=" + _getMerchantTrafficInfoByMerchantId__return);


        }
        {
        System.out.println("Invoking updateMerchantTraffic...");
        com.froad.client.merchantTraffic.MerchantTraffic _updateMerchantTraffic_arg0 = null;
        port.updateMerchantTraffic(_updateMerchantTraffic_arg0);


        }
        {
        System.out.println("Invoking getMerchantTrafficInfo...");
        java.lang.String _getMerchantTrafficInfo_arg0 = "";
        java.lang.String _getMerchantTrafficInfo_arg1 = "";
        java.util.List<com.froad.client.merchantTraffic.MerchantTraffic> _getMerchantTrafficInfo__return = port.getMerchantTrafficInfo(_getMerchantTrafficInfo_arg0, _getMerchantTrafficInfo_arg1);
        System.out.println("getMerchantTrafficInfo.result=" + _getMerchantTrafficInfo__return);


        }

        System.exit(0);
    }

}
