package com.froad.client.merchantUserSeller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-04-15T16:39:26.935+08:00
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://service.CB.froad.com/", name = "MerchantUserSellerService")
@XmlSeeAlso({ObjectFactory.class})
public interface MerchantUserSellerService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMerchantUserSellers", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.merchantUserSeller.GetMerchantUserSellers")
    @WebMethod
    @ResponseWrapper(localName = "getMerchantUserSellersResponse", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.merchantUserSeller.GetMerchantUserSellersResponse")
    public java.util.List<com.froad.client.merchantUserSeller.MerchantUserSeller> getMerchantUserSellers(
        @WebParam(name = "arg0", targetNamespace = "")
        com.froad.client.merchantUserSeller.MerchantUserSeller arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateByMerchantSeller", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.merchantUserSeller.UpdateByMerchantSeller")
    @WebMethod
    @ResponseWrapper(localName = "updateByMerchantSellerResponse", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.merchantUserSeller.UpdateByMerchantSellerResponse")
    public java.lang.Integer updateByMerchantSeller(
        @WebParam(name = "arg0", targetNamespace = "")
        com.froad.client.merchantUserSeller.MerchantUserSeller arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteByMerchantSeller", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.merchantUserSeller.DeleteByMerchantSeller")
    @WebMethod
    @ResponseWrapper(localName = "deleteByMerchantSellerResponse", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.merchantUserSeller.DeleteByMerchantSellerResponse")
    public java.lang.Integer deleteByMerchantSeller(
        @WebParam(name = "arg0", targetNamespace = "")
        com.froad.client.merchantUserSeller.MerchantUserSeller arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addMerchantUserSeller", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.merchantUserSeller.AddMerchantUserSeller")
    @WebMethod
    @ResponseWrapper(localName = "addMerchantUserSellerResponse", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.merchantUserSeller.AddMerchantUserSellerResponse")
    public java.lang.Integer addMerchantUserSeller(
        @WebParam(name = "arg0", targetNamespace = "")
        com.froad.client.merchantUserSeller.MerchantUserSeller arg0
    );
}
