package com.froad.client.tag;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-04-15T16:36:29.026+08:00
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://service.CB.froad.com/", name = "TagDistrictAService")
@XmlSeeAlso({ObjectFactory.class})
public interface TagDistrictAService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllTagDistrictA", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.tag.GetAllTagDistrictA")
    @WebMethod
    @ResponseWrapper(localName = "getAllTagDistrictAResponse", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.tag.GetAllTagDistrictAResponse")
    public java.util.List<com.froad.client.tag.TagDistrictA> getAllTagDistrictA();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllTagDistrictAByEnabled", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.tag.GetAllTagDistrictAByEnabled")
    @WebMethod
    @ResponseWrapper(localName = "getAllTagDistrictAByEnabledResponse", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.tag.GetAllTagDistrictAByEnabledResponse")
    public java.util.List<com.froad.client.tag.TagDistrictA> getAllTagDistrictAByEnabled();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTagDistrictAByValue", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.tag.GetTagDistrictAByValue")
    @WebMethod
    @ResponseWrapper(localName = "getTagDistrictAByValueResponse", targetNamespace = "http://service.CB.froad.com/", className = "com.froad.client.tag.GetTagDistrictAByValueResponse")
    public java.util.List<com.froad.client.tag.TagDistrictA> getTagDistrictAByValue(
        @WebParam(name = "arg0", targetNamespace = "")
        com.froad.client.tag.TagDistrictA arg0
    );
}
