
/*
 * 
 */

package com.froad.client.ruleDetailTemplet;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-04-15T16:37:09.463+08:00
 * Generated source version: 2.3.3
 * 
 */


@WebServiceClient(name = "RuleDetailTempletServiceImplService", 
                  wsdlLocation = "http://localhost:8989/fft_server/RuleDetailTempletService?wsdl",
                  targetNamespace = "http://impl.service.CB.froad.com/") 
public class RuleDetailTempletServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.CB.froad.com/", "RuleDetailTempletServiceImplService");
    public final static QName RuleDetailTempletServiceImplPort = new QName("http://impl.service.CB.froad.com/", "RuleDetailTempletServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8989/fft_server/RuleDetailTempletService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8989/fft_server/RuleDetailTempletService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public RuleDetailTempletServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RuleDetailTempletServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RuleDetailTempletServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns RuleDetailTempletService
     */
    @WebEndpoint(name = "RuleDetailTempletServiceImplPort")
    public RuleDetailTempletService getRuleDetailTempletServiceImplPort() {
        return super.getPort(RuleDetailTempletServiceImplPort, RuleDetailTempletService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RuleDetailTempletService
     */
    @WebEndpoint(name = "RuleDetailTempletServiceImplPort")
    public RuleDetailTempletService getRuleDetailTempletServiceImplPort(WebServiceFeature... features) {
        return super.getPort(RuleDetailTempletServiceImplPort, RuleDetailTempletService.class, features);
    }

}
