
/*
 * 
 */

package com.froad.client.user;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-04-15T16:36:16.396+08:00
 * Generated source version: 2.3.3
 * 
 */


@WebServiceClient(name = "MLoginManagerServiceImplService", 
                  wsdlLocation = "http://localhost:8989/fft_server/MLoginManager?wsdl",
                  targetNamespace = "http://impl.user.service.CB.froad.com/") 
public class MLoginManagerServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.user.service.CB.froad.com/", "MLoginManagerServiceImplService");
    public final static QName MLoginManagerServiceImplPort = new QName("http://impl.user.service.CB.froad.com/", "MLoginManagerServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8989/fft_server/MLoginManager?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8989/fft_server/MLoginManager?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MLoginManagerServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MLoginManagerServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MLoginManagerServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns MLoginManagerService
     */
    @WebEndpoint(name = "MLoginManagerServiceImplPort")
    public MLoginManagerService getMLoginManagerServiceImplPort() {
        return super.getPort(MLoginManagerServiceImplPort, MLoginManagerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MLoginManagerService
     */
    @WebEndpoint(name = "MLoginManagerServiceImplPort")
    public MLoginManagerService getMLoginManagerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MLoginManagerServiceImplPort, MLoginManagerService.class, features);
    }

}
