/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.froad.thrift.vo;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
/**
 * token检验返回对象
 * BankOperatorCheckVoRes
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-3-4")
public class BankOperatorCheckVoRes implements org.apache.thrift.TBase<BankOperatorCheckVoRes, BankOperatorCheckVoRes._Fields>, java.io.Serializable, Cloneable, Comparable<BankOperatorCheckVoRes> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BankOperatorCheckVoRes");

  private static final org.apache.thrift.protocol.TField RESULT_FIELD_DESC = new org.apache.thrift.protocol.TField("result", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField BANK_OPERATOR_FIELD_DESC = new org.apache.thrift.protocol.TField("bankOperator", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BankOperatorCheckVoResStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BankOperatorCheckVoResTupleSchemeFactory());
  }

  /**
   * 结果集vo
   */
  public com.froad.thrift.vo.ResultVo result; // required
  /**
   * 银行用户vo
   */
  public BankOperatorVo bankOperator; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 结果集vo
     */
    RESULT((short)1, "result"),
    /**
     * 银行用户vo
     */
    BANK_OPERATOR((short)2, "bankOperator");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESULT
          return RESULT;
        case 2: // BANK_OPERATOR
          return BANK_OPERATOR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESULT, new org.apache.thrift.meta_data.FieldMetaData("result", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.froad.thrift.vo.ResultVo.class)));
    tmpMap.put(_Fields.BANK_OPERATOR, new org.apache.thrift.meta_data.FieldMetaData("bankOperator", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "BankOperatorVo")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BankOperatorCheckVoRes.class, metaDataMap);
  }

  public BankOperatorCheckVoRes() {
  }

  public BankOperatorCheckVoRes(
    com.froad.thrift.vo.ResultVo result,
    BankOperatorVo bankOperator)
  {
    this();
    this.result = result;
    this.bankOperator = bankOperator;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BankOperatorCheckVoRes(BankOperatorCheckVoRes other) {
    if (other.isSetResult()) {
      this.result = new com.froad.thrift.vo.ResultVo(other.result);
    }
    if (other.isSetBankOperator()) {
      this.bankOperator = other.bankOperator;
    }
  }

  public BankOperatorCheckVoRes deepCopy() {
    return new BankOperatorCheckVoRes(this);
  }

  @Override
  public void clear() {
    this.result = null;
    this.bankOperator = null;
  }

  /**
   * 结果集vo
   */
  public com.froad.thrift.vo.ResultVo getResult() {
    return this.result;
  }

  /**
   * 结果集vo
   */
  public BankOperatorCheckVoRes setResult(com.froad.thrift.vo.ResultVo result) {
    this.result = result;
    return this;
  }

  public void unsetResult() {
    this.result = null;
  }

  /** Returns true if field result is set (has been assigned a value) and false otherwise */
  public boolean isSetResult() {
    return this.result != null;
  }

  public void setResultIsSet(boolean value) {
    if (!value) {
      this.result = null;
    }
  }

  /**
   * 银行用户vo
   */
  public BankOperatorVo getBankOperator() {
    return this.bankOperator;
  }

  /**
   * 银行用户vo
   */
  public BankOperatorCheckVoRes setBankOperator(BankOperatorVo bankOperator) {
    this.bankOperator = bankOperator;
    return this;
  }

  public void unsetBankOperator() {
    this.bankOperator = null;
  }

  /** Returns true if field bankOperator is set (has been assigned a value) and false otherwise */
  public boolean isSetBankOperator() {
    return this.bankOperator != null;
  }

  public void setBankOperatorIsSet(boolean value) {
    if (!value) {
      this.bankOperator = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESULT:
      if (value == null) {
        unsetResult();
      } else {
        setResult((com.froad.thrift.vo.ResultVo)value);
      }
      break;

    case BANK_OPERATOR:
      if (value == null) {
        unsetBankOperator();
      } else {
        setBankOperator((BankOperatorVo)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESULT:
      return getResult();

    case BANK_OPERATOR:
      return getBankOperator();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESULT:
      return isSetResult();
    case BANK_OPERATOR:
      return isSetBankOperator();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BankOperatorCheckVoRes)
      return this.equals((BankOperatorCheckVoRes)that);
    return false;
  }

  public boolean equals(BankOperatorCheckVoRes that) {
    if (that == null)
      return false;

    boolean this_present_result = true && this.isSetResult();
    boolean that_present_result = true && that.isSetResult();
    if (this_present_result || that_present_result) {
      if (!(this_present_result && that_present_result))
        return false;
      if (!this.result.equals(that.result))
        return false;
    }

    boolean this_present_bankOperator = true && this.isSetBankOperator();
    boolean that_present_bankOperator = true && that.isSetBankOperator();
    if (this_present_bankOperator || that_present_bankOperator) {
      if (!(this_present_bankOperator && that_present_bankOperator))
        return false;
      if (!this.bankOperator.equals(that.bankOperator))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_result = true && (isSetResult());
    list.add(present_result);
    if (present_result)
      list.add(result);

    boolean present_bankOperator = true && (isSetBankOperator());
    list.add(present_bankOperator);
    if (present_bankOperator)
      list.add(bankOperator);

    return list.hashCode();
  }

  @Override
  public int compareTo(BankOperatorCheckVoRes other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetResult()).compareTo(other.isSetResult());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResult()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.result, other.result);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBankOperator()).compareTo(other.isSetBankOperator());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBankOperator()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bankOperator, other.bankOperator);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BankOperatorCheckVoRes(");
    boolean first = true;

    sb.append("result:");
    if (this.result == null) {
      sb.append("null");
    } else {
      sb.append(this.result);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("bankOperator:");
    if (this.bankOperator == null) {
      sb.append("null");
    } else {
      sb.append(this.bankOperator);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (result != null) {
      result.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BankOperatorCheckVoResStandardSchemeFactory implements SchemeFactory {
    public BankOperatorCheckVoResStandardScheme getScheme() {
      return new BankOperatorCheckVoResStandardScheme();
    }
  }

  private static class BankOperatorCheckVoResStandardScheme extends StandardScheme<BankOperatorCheckVoRes> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BankOperatorCheckVoRes struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESULT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.result = new com.froad.thrift.vo.ResultVo();
              struct.result.read(iprot);
              struct.setResultIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BANK_OPERATOR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.bankOperator = new BankOperatorVo();
              struct.bankOperator.read(iprot);
              struct.setBankOperatorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BankOperatorCheckVoRes struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.result != null) {
        oprot.writeFieldBegin(RESULT_FIELD_DESC);
        struct.result.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.bankOperator != null) {
        oprot.writeFieldBegin(BANK_OPERATOR_FIELD_DESC);
        struct.bankOperator.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BankOperatorCheckVoResTupleSchemeFactory implements SchemeFactory {
    public BankOperatorCheckVoResTupleScheme getScheme() {
      return new BankOperatorCheckVoResTupleScheme();
    }
  }

  private static class BankOperatorCheckVoResTupleScheme extends TupleScheme<BankOperatorCheckVoRes> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BankOperatorCheckVoRes struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetResult()) {
        optionals.set(0);
      }
      if (struct.isSetBankOperator()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetResult()) {
        struct.result.write(oprot);
      }
      if (struct.isSetBankOperator()) {
        struct.bankOperator.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BankOperatorCheckVoRes struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.result = new com.froad.thrift.vo.ResultVo();
        struct.result.read(iprot);
        struct.setResultIsSet(true);
      }
      if (incoming.get(1)) {
        struct.bankOperator = new BankOperatorVo();
        struct.bankOperator.read(iprot);
        struct.setBankOperatorIsSet(true);
      }
    }
  }

}

