/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.froad.thrift.vo;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
/**
 * 字典类别Listvo
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-3-4")
public class DictionaryCategoryListVoRes implements org.apache.thrift.TBase<DictionaryCategoryListVoRes, DictionaryCategoryListVoRes._Fields>, java.io.Serializable, Cloneable, Comparable<DictionaryCategoryListVoRes> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DictionaryCategoryListVoRes");

  private static final org.apache.thrift.protocol.TField RESULT_VO_FIELD_DESC = new org.apache.thrift.protocol.TField("resultVo", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField DICTIONARY_CATEGORY_VO_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("dictionaryCategoryVoList", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DictionaryCategoryListVoResStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DictionaryCategoryListVoResTupleSchemeFactory());
  }

  /**
   * 返回结果
   */
  public com.froad.thrift.vo.ResultVo resultVo; // required
  /**
   * 字典类别集合
   */
  public List<DictionaryCategoryVo> dictionaryCategoryVoList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 返回结果
     */
    RESULT_VO((short)1, "resultVo"),
    /**
     * 字典类别集合
     */
    DICTIONARY_CATEGORY_VO_LIST((short)2, "dictionaryCategoryVoList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESULT_VO
          return RESULT_VO;
        case 2: // DICTIONARY_CATEGORY_VO_LIST
          return DICTIONARY_CATEGORY_VO_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESULT_VO, new org.apache.thrift.meta_data.FieldMetaData("resultVo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.froad.thrift.vo.ResultVo.class)));
    tmpMap.put(_Fields.DICTIONARY_CATEGORY_VO_LIST, new org.apache.thrift.meta_data.FieldMetaData("dictionaryCategoryVoList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, DictionaryCategoryVo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DictionaryCategoryListVoRes.class, metaDataMap);
  }

  public DictionaryCategoryListVoRes() {
  }

  public DictionaryCategoryListVoRes(
    com.froad.thrift.vo.ResultVo resultVo,
    List<DictionaryCategoryVo> dictionaryCategoryVoList)
  {
    this();
    this.resultVo = resultVo;
    this.dictionaryCategoryVoList = dictionaryCategoryVoList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DictionaryCategoryListVoRes(DictionaryCategoryListVoRes other) {
    if (other.isSetResultVo()) {
      this.resultVo = new com.froad.thrift.vo.ResultVo(other.resultVo);
    }
    if (other.isSetDictionaryCategoryVoList()) {
      List<DictionaryCategoryVo> __this__dictionaryCategoryVoList = new ArrayList<DictionaryCategoryVo>(other.dictionaryCategoryVoList.size());
      for (DictionaryCategoryVo other_element : other.dictionaryCategoryVoList) {
        __this__dictionaryCategoryVoList.add(new DictionaryCategoryVo(other_element));
      }
      this.dictionaryCategoryVoList = __this__dictionaryCategoryVoList;
    }
  }

  public DictionaryCategoryListVoRes deepCopy() {
    return new DictionaryCategoryListVoRes(this);
  }

  @Override
  public void clear() {
    this.resultVo = null;
    this.dictionaryCategoryVoList = null;
  }

  /**
   * 返回结果
   */
  public com.froad.thrift.vo.ResultVo getResultVo() {
    return this.resultVo;
  }

  /**
   * 返回结果
   */
  public DictionaryCategoryListVoRes setResultVo(com.froad.thrift.vo.ResultVo resultVo) {
    this.resultVo = resultVo;
    return this;
  }

  public void unsetResultVo() {
    this.resultVo = null;
  }

  /** Returns true if field resultVo is set (has been assigned a value) and false otherwise */
  public boolean isSetResultVo() {
    return this.resultVo != null;
  }

  public void setResultVoIsSet(boolean value) {
    if (!value) {
      this.resultVo = null;
    }
  }

  public int getDictionaryCategoryVoListSize() {
    return (this.dictionaryCategoryVoList == null) ? 0 : this.dictionaryCategoryVoList.size();
  }

  public java.util.Iterator<DictionaryCategoryVo> getDictionaryCategoryVoListIterator() {
    return (this.dictionaryCategoryVoList == null) ? null : this.dictionaryCategoryVoList.iterator();
  }

  public void addToDictionaryCategoryVoList(DictionaryCategoryVo elem) {
    if (this.dictionaryCategoryVoList == null) {
      this.dictionaryCategoryVoList = new ArrayList<DictionaryCategoryVo>();
    }
    this.dictionaryCategoryVoList.add(elem);
  }

  /**
   * 字典类别集合
   */
  public List<DictionaryCategoryVo> getDictionaryCategoryVoList() {
    return this.dictionaryCategoryVoList;
  }

  /**
   * 字典类别集合
   */
  public DictionaryCategoryListVoRes setDictionaryCategoryVoList(List<DictionaryCategoryVo> dictionaryCategoryVoList) {
    this.dictionaryCategoryVoList = dictionaryCategoryVoList;
    return this;
  }

  public void unsetDictionaryCategoryVoList() {
    this.dictionaryCategoryVoList = null;
  }

  /** Returns true if field dictionaryCategoryVoList is set (has been assigned a value) and false otherwise */
  public boolean isSetDictionaryCategoryVoList() {
    return this.dictionaryCategoryVoList != null;
  }

  public void setDictionaryCategoryVoListIsSet(boolean value) {
    if (!value) {
      this.dictionaryCategoryVoList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESULT_VO:
      if (value == null) {
        unsetResultVo();
      } else {
        setResultVo((com.froad.thrift.vo.ResultVo)value);
      }
      break;

    case DICTIONARY_CATEGORY_VO_LIST:
      if (value == null) {
        unsetDictionaryCategoryVoList();
      } else {
        setDictionaryCategoryVoList((List<DictionaryCategoryVo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESULT_VO:
      return getResultVo();

    case DICTIONARY_CATEGORY_VO_LIST:
      return getDictionaryCategoryVoList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESULT_VO:
      return isSetResultVo();
    case DICTIONARY_CATEGORY_VO_LIST:
      return isSetDictionaryCategoryVoList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DictionaryCategoryListVoRes)
      return this.equals((DictionaryCategoryListVoRes)that);
    return false;
  }

  public boolean equals(DictionaryCategoryListVoRes that) {
    if (that == null)
      return false;

    boolean this_present_resultVo = true && this.isSetResultVo();
    boolean that_present_resultVo = true && that.isSetResultVo();
    if (this_present_resultVo || that_present_resultVo) {
      if (!(this_present_resultVo && that_present_resultVo))
        return false;
      if (!this.resultVo.equals(that.resultVo))
        return false;
    }

    boolean this_present_dictionaryCategoryVoList = true && this.isSetDictionaryCategoryVoList();
    boolean that_present_dictionaryCategoryVoList = true && that.isSetDictionaryCategoryVoList();
    if (this_present_dictionaryCategoryVoList || that_present_dictionaryCategoryVoList) {
      if (!(this_present_dictionaryCategoryVoList && that_present_dictionaryCategoryVoList))
        return false;
      if (!this.dictionaryCategoryVoList.equals(that.dictionaryCategoryVoList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_resultVo = true && (isSetResultVo());
    list.add(present_resultVo);
    if (present_resultVo)
      list.add(resultVo);

    boolean present_dictionaryCategoryVoList = true && (isSetDictionaryCategoryVoList());
    list.add(present_dictionaryCategoryVoList);
    if (present_dictionaryCategoryVoList)
      list.add(dictionaryCategoryVoList);

    return list.hashCode();
  }

  @Override
  public int compareTo(DictionaryCategoryListVoRes other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetResultVo()).compareTo(other.isSetResultVo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResultVo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resultVo, other.resultVo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDictionaryCategoryVoList()).compareTo(other.isSetDictionaryCategoryVoList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDictionaryCategoryVoList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dictionaryCategoryVoList, other.dictionaryCategoryVoList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DictionaryCategoryListVoRes(");
    boolean first = true;

    sb.append("resultVo:");
    if (this.resultVo == null) {
      sb.append("null");
    } else {
      sb.append(this.resultVo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dictionaryCategoryVoList:");
    if (this.dictionaryCategoryVoList == null) {
      sb.append("null");
    } else {
      sb.append(this.dictionaryCategoryVoList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (resultVo != null) {
      resultVo.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DictionaryCategoryListVoResStandardSchemeFactory implements SchemeFactory {
    public DictionaryCategoryListVoResStandardScheme getScheme() {
      return new DictionaryCategoryListVoResStandardScheme();
    }
  }

  private static class DictionaryCategoryListVoResStandardScheme extends StandardScheme<DictionaryCategoryListVoRes> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DictionaryCategoryListVoRes struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESULT_VO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.resultVo = new com.froad.thrift.vo.ResultVo();
              struct.resultVo.read(iprot);
              struct.setResultVoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DICTIONARY_CATEGORY_VO_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.dictionaryCategoryVoList = new ArrayList<DictionaryCategoryVo>(_list0.size);
                DictionaryCategoryVo _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new DictionaryCategoryVo();
                  _elem1.read(iprot);
                  struct.dictionaryCategoryVoList.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setDictionaryCategoryVoListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DictionaryCategoryListVoRes struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.resultVo != null) {
        oprot.writeFieldBegin(RESULT_VO_FIELD_DESC);
        struct.resultVo.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.dictionaryCategoryVoList != null) {
        oprot.writeFieldBegin(DICTIONARY_CATEGORY_VO_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.dictionaryCategoryVoList.size()));
          for (DictionaryCategoryVo _iter3 : struct.dictionaryCategoryVoList)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DictionaryCategoryListVoResTupleSchemeFactory implements SchemeFactory {
    public DictionaryCategoryListVoResTupleScheme getScheme() {
      return new DictionaryCategoryListVoResTupleScheme();
    }
  }

  private static class DictionaryCategoryListVoResTupleScheme extends TupleScheme<DictionaryCategoryListVoRes> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DictionaryCategoryListVoRes struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetResultVo()) {
        optionals.set(0);
      }
      if (struct.isSetDictionaryCategoryVoList()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetResultVo()) {
        struct.resultVo.write(oprot);
      }
      if (struct.isSetDictionaryCategoryVoList()) {
        {
          oprot.writeI32(struct.dictionaryCategoryVoList.size());
          for (DictionaryCategoryVo _iter4 : struct.dictionaryCategoryVoList)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DictionaryCategoryListVoRes struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.resultVo = new com.froad.thrift.vo.ResultVo();
        struct.resultVo.read(iprot);
        struct.setResultVoIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.dictionaryCategoryVoList = new ArrayList<DictionaryCategoryVo>(_list5.size);
          DictionaryCategoryVo _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new DictionaryCategoryVo();
            _elem6.read(iprot);
            struct.dictionaryCategoryVoList.add(_elem6);
          }
        }
        struct.setDictionaryCategoryVoListIsSet(true);
      }
    }
  }

}

