/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.froad.thrift.vo;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
/**
 * 商户用户分页的响应
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-3-4")
public class MerchantUserPageVoRes implements org.apache.thrift.TBase<MerchantUserPageVoRes, MerchantUserPageVoRes._Fields>, java.io.Serializable, Cloneable, Comparable<MerchantUserPageVoRes> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MerchantUserPageVoRes");

  private static final org.apache.thrift.protocol.TField PAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("page", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField MERCHANT_USER_VO_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("merchantUserVoList", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MerchantUserPageVoResStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MerchantUserPageVoResTupleSchemeFactory());
  }

  /**
   * 分页基础信息
   */
  public com.froad.thrift.vo.PageVo page; // required
  /**
   * 商户用户信息列表
   */
  public List<MerchantUserVo> merchantUserVoList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 分页基础信息
     */
    PAGE((short)1, "page"),
    /**
     * 商户用户信息列表
     */
    MERCHANT_USER_VO_LIST((short)2, "merchantUserVoList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PAGE
          return PAGE;
        case 2: // MERCHANT_USER_VO_LIST
          return MERCHANT_USER_VO_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PAGE, new org.apache.thrift.meta_data.FieldMetaData("page", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.froad.thrift.vo.PageVo.class)));
    tmpMap.put(_Fields.MERCHANT_USER_VO_LIST, new org.apache.thrift.meta_data.FieldMetaData("merchantUserVoList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MerchantUserVo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MerchantUserPageVoRes.class, metaDataMap);
  }

  public MerchantUserPageVoRes() {
  }

  public MerchantUserPageVoRes(
    com.froad.thrift.vo.PageVo page,
    List<MerchantUserVo> merchantUserVoList)
  {
    this();
    this.page = page;
    this.merchantUserVoList = merchantUserVoList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MerchantUserPageVoRes(MerchantUserPageVoRes other) {
    if (other.isSetPage()) {
      this.page = new com.froad.thrift.vo.PageVo(other.page);
    }
    if (other.isSetMerchantUserVoList()) {
      List<MerchantUserVo> __this__merchantUserVoList = new ArrayList<MerchantUserVo>(other.merchantUserVoList.size());
      for (MerchantUserVo other_element : other.merchantUserVoList) {
        __this__merchantUserVoList.add(new MerchantUserVo(other_element));
      }
      this.merchantUserVoList = __this__merchantUserVoList;
    }
  }

  public MerchantUserPageVoRes deepCopy() {
    return new MerchantUserPageVoRes(this);
  }

  @Override
  public void clear() {
    this.page = null;
    this.merchantUserVoList = null;
  }

  /**
   * 分页基础信息
   */
  public com.froad.thrift.vo.PageVo getPage() {
    return this.page;
  }

  /**
   * 分页基础信息
   */
  public MerchantUserPageVoRes setPage(com.froad.thrift.vo.PageVo page) {
    this.page = page;
    return this;
  }

  public void unsetPage() {
    this.page = null;
  }

  /** Returns true if field page is set (has been assigned a value) and false otherwise */
  public boolean isSetPage() {
    return this.page != null;
  }

  public void setPageIsSet(boolean value) {
    if (!value) {
      this.page = null;
    }
  }

  public int getMerchantUserVoListSize() {
    return (this.merchantUserVoList == null) ? 0 : this.merchantUserVoList.size();
  }

  public java.util.Iterator<MerchantUserVo> getMerchantUserVoListIterator() {
    return (this.merchantUserVoList == null) ? null : this.merchantUserVoList.iterator();
  }

  public void addToMerchantUserVoList(MerchantUserVo elem) {
    if (this.merchantUserVoList == null) {
      this.merchantUserVoList = new ArrayList<MerchantUserVo>();
    }
    this.merchantUserVoList.add(elem);
  }

  /**
   * 商户用户信息列表
   */
  public List<MerchantUserVo> getMerchantUserVoList() {
    return this.merchantUserVoList;
  }

  /**
   * 商户用户信息列表
   */
  public MerchantUserPageVoRes setMerchantUserVoList(List<MerchantUserVo> merchantUserVoList) {
    this.merchantUserVoList = merchantUserVoList;
    return this;
  }

  public void unsetMerchantUserVoList() {
    this.merchantUserVoList = null;
  }

  /** Returns true if field merchantUserVoList is set (has been assigned a value) and false otherwise */
  public boolean isSetMerchantUserVoList() {
    return this.merchantUserVoList != null;
  }

  public void setMerchantUserVoListIsSet(boolean value) {
    if (!value) {
      this.merchantUserVoList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PAGE:
      if (value == null) {
        unsetPage();
      } else {
        setPage((com.froad.thrift.vo.PageVo)value);
      }
      break;

    case MERCHANT_USER_VO_LIST:
      if (value == null) {
        unsetMerchantUserVoList();
      } else {
        setMerchantUserVoList((List<MerchantUserVo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PAGE:
      return getPage();

    case MERCHANT_USER_VO_LIST:
      return getMerchantUserVoList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PAGE:
      return isSetPage();
    case MERCHANT_USER_VO_LIST:
      return isSetMerchantUserVoList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MerchantUserPageVoRes)
      return this.equals((MerchantUserPageVoRes)that);
    return false;
  }

  public boolean equals(MerchantUserPageVoRes that) {
    if (that == null)
      return false;

    boolean this_present_page = true && this.isSetPage();
    boolean that_present_page = true && that.isSetPage();
    if (this_present_page || that_present_page) {
      if (!(this_present_page && that_present_page))
        return false;
      if (!this.page.equals(that.page))
        return false;
    }

    boolean this_present_merchantUserVoList = true && this.isSetMerchantUserVoList();
    boolean that_present_merchantUserVoList = true && that.isSetMerchantUserVoList();
    if (this_present_merchantUserVoList || that_present_merchantUserVoList) {
      if (!(this_present_merchantUserVoList && that_present_merchantUserVoList))
        return false;
      if (!this.merchantUserVoList.equals(that.merchantUserVoList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_page = true && (isSetPage());
    list.add(present_page);
    if (present_page)
      list.add(page);

    boolean present_merchantUserVoList = true && (isSetMerchantUserVoList());
    list.add(present_merchantUserVoList);
    if (present_merchantUserVoList)
      list.add(merchantUserVoList);

    return list.hashCode();
  }

  @Override
  public int compareTo(MerchantUserPageVoRes other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPage()).compareTo(other.isSetPage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.page, other.page);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMerchantUserVoList()).compareTo(other.isSetMerchantUserVoList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMerchantUserVoList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.merchantUserVoList, other.merchantUserVoList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MerchantUserPageVoRes(");
    boolean first = true;

    sb.append("page:");
    if (this.page == null) {
      sb.append("null");
    } else {
      sb.append(this.page);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("merchantUserVoList:");
    if (this.merchantUserVoList == null) {
      sb.append("null");
    } else {
      sb.append(this.merchantUserVoList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (page != null) {
      page.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MerchantUserPageVoResStandardSchemeFactory implements SchemeFactory {
    public MerchantUserPageVoResStandardScheme getScheme() {
      return new MerchantUserPageVoResStandardScheme();
    }
  }

  private static class MerchantUserPageVoResStandardScheme extends StandardScheme<MerchantUserPageVoRes> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MerchantUserPageVoRes struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.page = new com.froad.thrift.vo.PageVo();
              struct.page.read(iprot);
              struct.setPageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MERCHANT_USER_VO_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.merchantUserVoList = new ArrayList<MerchantUserVo>(_list0.size);
                MerchantUserVo _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new MerchantUserVo();
                  _elem1.read(iprot);
                  struct.merchantUserVoList.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setMerchantUserVoListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MerchantUserPageVoRes struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.page != null) {
        oprot.writeFieldBegin(PAGE_FIELD_DESC);
        struct.page.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.merchantUserVoList != null) {
        oprot.writeFieldBegin(MERCHANT_USER_VO_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.merchantUserVoList.size()));
          for (MerchantUserVo _iter3 : struct.merchantUserVoList)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MerchantUserPageVoResTupleSchemeFactory implements SchemeFactory {
    public MerchantUserPageVoResTupleScheme getScheme() {
      return new MerchantUserPageVoResTupleScheme();
    }
  }

  private static class MerchantUserPageVoResTupleScheme extends TupleScheme<MerchantUserPageVoRes> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MerchantUserPageVoRes struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPage()) {
        optionals.set(0);
      }
      if (struct.isSetMerchantUserVoList()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPage()) {
        struct.page.write(oprot);
      }
      if (struct.isSetMerchantUserVoList()) {
        {
          oprot.writeI32(struct.merchantUserVoList.size());
          for (MerchantUserVo _iter4 : struct.merchantUserVoList)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MerchantUserPageVoRes struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.page = new com.froad.thrift.vo.PageVo();
        struct.page.read(iprot);
        struct.setPageIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.merchantUserVoList = new ArrayList<MerchantUserVo>(_list5.size);
          MerchantUserVo _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new MerchantUserVo();
            _elem6.read(iprot);
            struct.merchantUserVoList.add(_elem6);
          }
        }
        struct.setMerchantUserVoListIsSet(true);
      }
    }
  }

}

