/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.froad.thrift.vo;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
/**
 * 商品品论与回复表信息分页信息
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-3-4")
public class ProductCommentPageVo implements org.apache.thrift.TBase<ProductCommentPageVo, ProductCommentPageVo._Fields>, java.io.Serializable, Cloneable, Comparable<ProductCommentPageVo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ProductCommentPageVo");

  private static final org.apache.thrift.protocol.TField PAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("page", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField PRODUCT_COMMENT_VO_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("ProductCommentVoList", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ProductCommentPageVoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ProductCommentPageVoTupleSchemeFactory());
  }

  public com.froad.thrift.vo.PageVo page; // required
  public List<ProductCommentVo> ProductCommentVoList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PAGE((short)1, "page"),
    PRODUCT_COMMENT_VO_LIST((short)2, "ProductCommentVoList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PAGE
          return PAGE;
        case 2: // PRODUCT_COMMENT_VO_LIST
          return PRODUCT_COMMENT_VO_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PAGE, new org.apache.thrift.meta_data.FieldMetaData("page", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.froad.thrift.vo.PageVo.class)));
    tmpMap.put(_Fields.PRODUCT_COMMENT_VO_LIST, new org.apache.thrift.meta_data.FieldMetaData("ProductCommentVoList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ProductCommentVo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ProductCommentPageVo.class, metaDataMap);
  }

  public ProductCommentPageVo() {
  }

  public ProductCommentPageVo(
    com.froad.thrift.vo.PageVo page,
    List<ProductCommentVo> ProductCommentVoList)
  {
    this();
    this.page = page;
    this.ProductCommentVoList = ProductCommentVoList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ProductCommentPageVo(ProductCommentPageVo other) {
    if (other.isSetPage()) {
      this.page = new com.froad.thrift.vo.PageVo(other.page);
    }
    if (other.isSetProductCommentVoList()) {
      List<ProductCommentVo> __this__ProductCommentVoList = new ArrayList<ProductCommentVo>(other.ProductCommentVoList.size());
      for (ProductCommentVo other_element : other.ProductCommentVoList) {
        __this__ProductCommentVoList.add(new ProductCommentVo(other_element));
      }
      this.ProductCommentVoList = __this__ProductCommentVoList;
    }
  }

  public ProductCommentPageVo deepCopy() {
    return new ProductCommentPageVo(this);
  }

  @Override
  public void clear() {
    this.page = null;
    this.ProductCommentVoList = null;
  }

  public com.froad.thrift.vo.PageVo getPage() {
    return this.page;
  }

  public ProductCommentPageVo setPage(com.froad.thrift.vo.PageVo page) {
    this.page = page;
    return this;
  }

  public void unsetPage() {
    this.page = null;
  }

  /** Returns true if field page is set (has been assigned a value) and false otherwise */
  public boolean isSetPage() {
    return this.page != null;
  }

  public void setPageIsSet(boolean value) {
    if (!value) {
      this.page = null;
    }
  }

  public int getProductCommentVoListSize() {
    return (this.ProductCommentVoList == null) ? 0 : this.ProductCommentVoList.size();
  }

  public java.util.Iterator<ProductCommentVo> getProductCommentVoListIterator() {
    return (this.ProductCommentVoList == null) ? null : this.ProductCommentVoList.iterator();
  }

  public void addToProductCommentVoList(ProductCommentVo elem) {
    if (this.ProductCommentVoList == null) {
      this.ProductCommentVoList = new ArrayList<ProductCommentVo>();
    }
    this.ProductCommentVoList.add(elem);
  }

  public List<ProductCommentVo> getProductCommentVoList() {
    return this.ProductCommentVoList;
  }

  public ProductCommentPageVo setProductCommentVoList(List<ProductCommentVo> ProductCommentVoList) {
    this.ProductCommentVoList = ProductCommentVoList;
    return this;
  }

  public void unsetProductCommentVoList() {
    this.ProductCommentVoList = null;
  }

  /** Returns true if field ProductCommentVoList is set (has been assigned a value) and false otherwise */
  public boolean isSetProductCommentVoList() {
    return this.ProductCommentVoList != null;
  }

  public void setProductCommentVoListIsSet(boolean value) {
    if (!value) {
      this.ProductCommentVoList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PAGE:
      if (value == null) {
        unsetPage();
      } else {
        setPage((com.froad.thrift.vo.PageVo)value);
      }
      break;

    case PRODUCT_COMMENT_VO_LIST:
      if (value == null) {
        unsetProductCommentVoList();
      } else {
        setProductCommentVoList((List<ProductCommentVo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PAGE:
      return getPage();

    case PRODUCT_COMMENT_VO_LIST:
      return getProductCommentVoList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PAGE:
      return isSetPage();
    case PRODUCT_COMMENT_VO_LIST:
      return isSetProductCommentVoList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ProductCommentPageVo)
      return this.equals((ProductCommentPageVo)that);
    return false;
  }

  public boolean equals(ProductCommentPageVo that) {
    if (that == null)
      return false;

    boolean this_present_page = true && this.isSetPage();
    boolean that_present_page = true && that.isSetPage();
    if (this_present_page || that_present_page) {
      if (!(this_present_page && that_present_page))
        return false;
      if (!this.page.equals(that.page))
        return false;
    }

    boolean this_present_ProductCommentVoList = true && this.isSetProductCommentVoList();
    boolean that_present_ProductCommentVoList = true && that.isSetProductCommentVoList();
    if (this_present_ProductCommentVoList || that_present_ProductCommentVoList) {
      if (!(this_present_ProductCommentVoList && that_present_ProductCommentVoList))
        return false;
      if (!this.ProductCommentVoList.equals(that.ProductCommentVoList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_page = true && (isSetPage());
    list.add(present_page);
    if (present_page)
      list.add(page);

    boolean present_ProductCommentVoList = true && (isSetProductCommentVoList());
    list.add(present_ProductCommentVoList);
    if (present_ProductCommentVoList)
      list.add(ProductCommentVoList);

    return list.hashCode();
  }

  @Override
  public int compareTo(ProductCommentPageVo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPage()).compareTo(other.isSetPage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.page, other.page);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProductCommentVoList()).compareTo(other.isSetProductCommentVoList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProductCommentVoList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ProductCommentVoList, other.ProductCommentVoList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ProductCommentPageVo(");
    boolean first = true;

    sb.append("page:");
    if (this.page == null) {
      sb.append("null");
    } else {
      sb.append(this.page);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ProductCommentVoList:");
    if (this.ProductCommentVoList == null) {
      sb.append("null");
    } else {
      sb.append(this.ProductCommentVoList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (page != null) {
      page.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ProductCommentPageVoStandardSchemeFactory implements SchemeFactory {
    public ProductCommentPageVoStandardScheme getScheme() {
      return new ProductCommentPageVoStandardScheme();
    }
  }

  private static class ProductCommentPageVoStandardScheme extends StandardScheme<ProductCommentPageVo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ProductCommentPageVo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.page = new com.froad.thrift.vo.PageVo();
              struct.page.read(iprot);
              struct.setPageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PRODUCT_COMMENT_VO_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list80 = iprot.readListBegin();
                struct.ProductCommentVoList = new ArrayList<ProductCommentVo>(_list80.size);
                ProductCommentVo _elem81;
                for (int _i82 = 0; _i82 < _list80.size; ++_i82)
                {
                  _elem81 = new ProductCommentVo();
                  _elem81.read(iprot);
                  struct.ProductCommentVoList.add(_elem81);
                }
                iprot.readListEnd();
              }
              struct.setProductCommentVoListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ProductCommentPageVo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.page != null) {
        oprot.writeFieldBegin(PAGE_FIELD_DESC);
        struct.page.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.ProductCommentVoList != null) {
        oprot.writeFieldBegin(PRODUCT_COMMENT_VO_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.ProductCommentVoList.size()));
          for (ProductCommentVo _iter83 : struct.ProductCommentVoList)
          {
            _iter83.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ProductCommentPageVoTupleSchemeFactory implements SchemeFactory {
    public ProductCommentPageVoTupleScheme getScheme() {
      return new ProductCommentPageVoTupleScheme();
    }
  }

  private static class ProductCommentPageVoTupleScheme extends TupleScheme<ProductCommentPageVo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ProductCommentPageVo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPage()) {
        optionals.set(0);
      }
      if (struct.isSetProductCommentVoList()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPage()) {
        struct.page.write(oprot);
      }
      if (struct.isSetProductCommentVoList()) {
        {
          oprot.writeI32(struct.ProductCommentVoList.size());
          for (ProductCommentVo _iter84 : struct.ProductCommentVoList)
          {
            _iter84.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ProductCommentPageVo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.page = new com.froad.thrift.vo.PageVo();
        struct.page.read(iprot);
        struct.setPageIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list85 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.ProductCommentVoList = new ArrayList<ProductCommentVo>(_list85.size);
          ProductCommentVo _elem86;
          for (int _i87 = 0; _i87 < _list85.size; ++_i87)
          {
            _elem86 = new ProductCommentVo();
            _elem86.read(iprot);
            struct.ProductCommentVoList.add(_elem86);
          }
        }
        struct.setProductCommentVoListIsSet(true);
      }
    }
  }

}

