//商品团购架
CREATE TABLE `goods_group_rack` (
  `id` int(32) NOT NULL auto_increment COMMENT '主键 自增100001001开始',
  `goods_id` varchar(32) NOT NULL COMMENT '商品ID',
  `group_price` varchar(32) default '0' COMMENT '团购价',
  `per_number` varchar(32) default '0' COMMENT '每人限购',
  `permin_number` varchar(32) default '1' COMMENT '最低购买',
  `begin_time` varchar(32) default NULL COMMENT '团购开始时间',
  `end_time` varchar(32) default NULL COMMENT '团购结束时间',
  `ticket_begin_time` varchar(32) default NULL COMMENT '团购卷使用有效期开始时间',
  `ticket_end_time` varchar(32) default NULL COMMENT '团购卷使用有效期结束时间',
  `colse_bill_begin_time` varchar(32) default NULL COMMENT '关帐开始时间（期间不允许退款）',
  `colse_bill_end_time` varchar(32) default NULL COMMENT '关帐结束时间（期间不允许退款）',
  `seo_title` varchar(255) default NULL COMMENT '推广标题',
  `seo_keyword` varchar(255) default NULL COMMENT '推广关键字',
  `seo_description` varchar(1024) default NULL COMMENT '推广描述',
  `is_rack` varchar(32) default '0' COMMENT '是否上架 0-否 1-是',
  `is_allowrefund` varchar(32) default '0' COMMENT '是否同意退款 0-否 1-是',
  `rack_time` varchar(32) default NULL COMMENT '上架时间',
  `inspectors` varchar(32) default NULL COMMENT '审核人',
  `market_total_number` varchar(32) default '0' COMMENT '销售数量',
  `refund_total_number` varchar(32) default '0' COMMENT '退款数量',
  `is_cash` varchar(32) default '0' COMMENT '是否启用现金 0-否 1-是',
  `is_fft_point` varchar(32) default '0' COMMENT '是否启用分分通积分 0-否 1-是',
  `is_bank_point` varchar(32) default '0' COMMENT '是否启用银行积分 0-否 1-是',
  `is_fftpoint_cash` varchar(32) default '0' COMMENT '是否启用分分通积分+现金 0-否 1-是',
  `is_bankpoint_cash` varchar(32) default '0' COMMENT '是否启用银行积分+现金 0-否 1-是',
  `is_fftpointcash_ratio_pricing` varchar(32) default '0' COMMENT '是否启用分分通积分+现金比例定价 0-否 1-是',
  `is_bankpointcash_ratio_pricing` varchar(32) default '0' COMMENT '是否启用银行积分+现金比例定价 0-否 1-是',
  `cash_pricing` varchar(32) default NULL COMMENT '现金定价',
  `fft_point_pricing` varchar(32) default NULL COMMENT '分分通积分定价',
  `bank_point_pricing` varchar(32) default NULL COMMENT '银行积分定价',
  `fftpoint_cash_pricing` varchar(32) default NULL COMMENT '分分通积分和现金定价',
  `bankpoint_cash_pricing` varchar(32) default NULL COMMENT '银行积分和现金定价',
  `fftpointcash_ratio_pricing` varchar(32) default NULL COMMENT '分分通+现金比例定价',
  `bankpointcash_ratio_pricing` varchar(32) default NULL COMMENT '银行+现金比例定价',
  `state` varchar(32) default '10' COMMENT '状态(10-创建，20-录入，30-启用，40-停用，50-删除)',
  `create_time` varchar(32) default NULL COMMENT '创建时间',
  `update_time` varchar(32) default NULL COMMENT '更新时间',
  `remark` varchar(255) default NULL COMMENT '备注',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=100001001 DEFAULT CHARSET=utf8;

