
package com.froad.client.merchantTrafficMAP;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-04-15T16:38:12.592+08:00
 * Generated source version: 2.3.3
 * 
 */
public final class MerchantTrafficMAPService_MerchantTrafficMAPServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.CB.froad.com/", "MerchantTrafficMAPServiceImplService");

    private MerchantTrafficMAPService_MerchantTrafficMAPServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MerchantTrafficMAPServiceImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MerchantTrafficMAPServiceImplService ss = new MerchantTrafficMAPServiceImplService(wsdlURL, SERVICE_NAME);
        MerchantTrafficMAPService port = ss.getMerchantTrafficMAPServiceImplPort();  
        
        {
        System.out.println("Invoking addMerchantTrafficMAP...");
        com.froad.client.merchantTrafficMAP.MerchantTrafficMAP _addMerchantTrafficMAP_arg0 = null;
        java.lang.Integer _addMerchantTrafficMAP__return = port.addMerchantTrafficMAP(_addMerchantTrafficMAP_arg0);
        System.out.println("addMerchantTrafficMAP.result=" + _addMerchantTrafficMAP__return);


        }
        {
        System.out.println("Invoking getMerchantTrafficMapByUserId...");
        java.lang.String _getMerchantTrafficMapByUserId_arg0 = "";
        com.froad.client.merchantTrafficMAP.MerchantTrafficMAP _getMerchantTrafficMapByUserId__return = port.getMerchantTrafficMapByUserId(_getMerchantTrafficMapByUserId_arg0);
        System.out.println("getMerchantTrafficMapByUserId.result=" + _getMerchantTrafficMapByUserId__return);


        }
        {
        System.out.println("Invoking updateMerchantTrafficMAP...");
        com.froad.client.merchantTrafficMAP.MerchantTrafficMAP _updateMerchantTrafficMAP_arg0 = null;
        boolean _updateMerchantTrafficMAP__return = port.updateMerchantTrafficMAP(_updateMerchantTrafficMAP_arg0);
        System.out.println("updateMerchantTrafficMAP.result=" + _updateMerchantTrafficMAP__return);


        }
        {
        System.out.println("Invoking getMerchantTrafficMapByMerchantId...");
        java.lang.String _getMerchantTrafficMapByMerchantId_arg0 = "";
        com.froad.client.merchantTrafficMAP.MerchantTrafficMAP _getMerchantTrafficMapByMerchantId__return = port.getMerchantTrafficMapByMerchantId(_getMerchantTrafficMapByMerchantId_arg0);
        System.out.println("getMerchantTrafficMapByMerchantId.result=" + _getMerchantTrafficMapByMerchantId__return);


        }

        System.exit(0);
    }

}
